//Test script generated by ChatGPT
import { test, expect } from '@playwright/test';

test('Search flights from Portland to Rome and validate 5 flights are displayed', async ({ page }) => {
  // Navigate to BlazeDemo
  await page.goto('https://blazedemo.com');

  // Select departure city
  await page.selectOption('select[name="fromPort"]', {
    label: 'Portland',
  });

  // Select destination city
  await page.selectOption('select[name="toPort"]', {
    label: 'Rome',
  });

  // Click Find Flights
  await page.getByRole('button', { name: 'Find Flights' }).click();

  // Verify the results page
  await expect(page).toHaveURL(/reserve\.php/);

  // Count the flight rows (excluding the header)
  const flightRows = page.locator('table tbody tr');

  // Validate exactly 5 flights are displayed
  await expect(flightRows).toHaveCount(5);
});